backend:
  name: git-gateway
  branch: master

media_folder: public/images
public_folder: /images

collections:
  - name: 'page'
    label: 'Pages' # Used in the UI
    folder: 'cms/pages' # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: '{{slug}}'
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - { label: 'Page Title', name: 'title', widget: 'string' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Main Content', name: 'content', widget: 'markdown' }
      - {
          label: 'Carousel',
          name: 'carousel',
          widget: 'list',
          summary: '{{fields.image}}',
          field: { label: Image, name: image, widget: image },
        }
      - label: 'Content Row'
        name: 'contentRow'
        widget: 'list'
        fields:
          - { label: 'Content', name: 'content', widget: 'markdown' }
          - { label: 'image', name: 'image', widget: 'image' }

  - name: 'homepage'
    label: 'Homepage'
    folder: 'cms/homepage'
    fields:
      - { label: 'Page Title', name: 'title', widget: 'string' }
      - {
          label: 'Homepage Carousel',
          name: 'carousel',
          widget: 'list',
          field: { label: Image, name: image, widget: image },
        }
